import{a as b,S as L,i as l}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();const S="55630526-f44120b4f4ecc6b1cd7cfb12b",C="https://pixabay.com/api/";async function p(r,o){return await b(C,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),c=document.querySelector(".btn-loader"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
        </a>

        <div class="info">
          <p>Likes<span>${t.likes}</span></p>
          <p>Views <span>${t.views}</span></p>
          <p>Comments <span>${t.comments}</span></p>
          <p>Downloads <span>${t.downloads}</span></p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),q.refresh()}function v(){f.innerHTML=""}function y(){g.style.display="block"}function m(){g.style.display="none"}function B(){c.classList.remove("hidden"),c.style.display="block"}function w(){c.classList.add("hidden"),c.style.display="none"}const E=document.querySelector(".form"),u=document.querySelector(".btn-loader");let n=1,i="";E.addEventListener("submit",P);u.addEventListener("click",R);async function P(r){if(r.preventDefault(),v(),w(),i=r.target.elements["search-text"].value.trim(),!!i){y();try{const o=await p(i,n=1),t=o.data.hits;if(!t.length){l.show({titleColor:"white",position:"topRight",title:"Error",backgroundColor:"red",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t),o.data.totalHits>t.length&&B()}catch{l.show({titleColor:"white",position:"topRight",title:"Error",backgroundColor:"red",messageColor:"white",message:"Something went wrong. Please try again later."})}finally{r.target.reset(),m()}}}async function R(){n++,u.disabled=!0,y();try{const r=await p(i,n),o=r.data.hits;h(o);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),n*15>=r.data.totalHits&&(w(),l.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.show({title:"Error",message:"Something went wrong! Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{u.disabled=!1,m()}}
//# sourceMappingURL=index.js.map
