import{a as L,S as C,i}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const S="55630526-f44120b4f4ecc6b1cd7cfb12b",q="https://pixabay.com/api/";async function g(a,o){return await L(q,{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),c=document.querySelector(".btn-loader"),P=new C(".gallery a",{captionsData:"alt",captionDelay:250});function f(a){const o=a.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
        </a>

        <div class="info">
          <p>Likes<span>${t.likes}</span></p>
          <p>Views <span>${t.views}</span></p>
          <p>Comments <span>${t.comments}</span></p>
          <p>Downloads <span>${t.downloads}</span></p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",o),P.refresh()}function v(){h.innerHTML=""}function m(){y.style.display="block"}function w(){y.style.display="none"}function b(){c.classList.remove("hidden"),c.style.display="block"}function d(){c.classList.add("hidden"),c.style.display="none"}const E=document.querySelector(".form"),p=document.querySelector(".btn-loader");let s=1,l="";E.addEventListener("submit",B);p.addEventListener("click",M);async function B(a){if(a.preventDefault(),v(),d(),l=a.target.elements["search-text"].value.trim(),!!l){s=1,m();try{const o=await g(l,s),t=o.data.hits,n=o.data.totalHits;if(!t.length){i.show({titleColor:"white",position:"topRight",title:"Error",backgroundColor:"red",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!"});return}f(t);const e=Math.ceil(n/15);s<e?b():(d(),i.show({titleColor:"white",position:"topRight",title:"Error",backgroundColor:"red",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!"}))}catch{i.show({titleColor:"white",position:"topRight",title:"Error",backgroundColor:"red",messageColor:"white",message:"Something went wrong. Please try again later."})}finally{w(),a.target.reset()}}}async function M(){s++,p.disabled=!0,m(),d();try{const a=await g(l,s),o=a.data.hits,t=a.data.totalHits;f(o);const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"});const r=Math.ceil(t/15);s>=r?(d(),i.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{i.show({title:"Error",message:"Something went wrong! Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{p.disabled=!1,w()}}
//# sourceMappingURL=index.js.map
